#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013, marmuta
#
# This file is part of pypredict, Onboard.
#
# Onboard is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Onboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


import os
import sys
import random
from optparse import OptionParser

from pypredict import *


def main():
    parser = OptionParser(usage="Usage: %prog [options] text-file")
    parser.add_option("-i", "--in-place",
              action="store_true", dest="in_place", default=False,
              help="overwrite the input file")
    parser.add_option("-p", "--paragraphs",
              action="store_true", dest="paragraphs", default=False,
              help="save all sentences as paragraphs (extra newline)")
    options, args = parser.parse_args()
    in_place = options.in_place
    paragraphs = options.paragraphs

    filename = args[0]

    text = read_corpus(filename)
    sentences, spans = split_sentences(text)

    random.seed()
    random.shuffle(sentences)

    if in_place:
        with codecs.open(filename, "w", encoding='utf-8') as f:
            for s in sentences:
                f.write(s + "\n")
                if paragraphs:
                    f.write("\n")
    else:
        for s in sentences:
            print(s)
            if paragraphs:
                print()

if __name__ == '__main__':
    main()

