#! /usr/bin/python3

import re
import shutil
from urllib.parse import urlparse, urlunparse
from urllib.request import urlopen

import apt
import apt_pkg

ARCH_TO_EFI_NAME = {
    'amd64': 'x64',
    'arm64': 'aa64',
}
arch = apt_pkg.config['Apt::Architecture']
efi_name = ARCH_TO_EFI_NAME[arch]
cache = apt.Cache()
grub_efi = cache["grub-efi-%s" % (arch)].candidate
pool_parsed = urlparse(grub_efi.uri)
dists_dir = "/dists/%s/main/uefi/grub2-%s/current/" % (
    grub_efi.origins[0].archive, grub_efi.architecture)

for base in (
        "gcd%s.efi.signed" % (efi_name),
        "grub%s.efi.signed" % (efi_name),
        "grubnet%s.efi.signed" % (efi_name),
        "version",
        ):
    dists_parsed = list(pool_parsed)
    dists_parsed[2] = re.sub(r"/pool/.*", dists_dir + base, dists_parsed[2])
    dists_uri = urlunparse(dists_parsed)
    print("Downloading %s ..." % dists_uri)
    with urlopen(dists_uri) as dists, open(base, "wb") as out:
        shutil.copyfileobj(dists, out)
