const char *strings[] = {
  _("Applications"), _("applications"),	 
  _("Desktop"), _("desktop"),	 
  _("Documents"), _("documents"),
  _("Download"), _("download"), 
  _("Downloads"), _("downloads"), 
  _("Movies"), _("movies"),	 
  _("Music"), _("music"),	 
  _("Photos"), _("photos"),	 
  _("Pictures"), _("pictures"), 
  _("Projects"), _("projects"), 
  _("Public"),  _("public"),
  _("Share"),  _("share"),
  _("Templates"), _("templates"),
  _("Videos"), _("videos"),   
};
