#!/bin/sh
# If you are looking to change accessibility profile settings, please look in
# bin/casper-a11y-enable.

. /usr/share/debconf/confmodule
. /etc/casper.conf

PREREQ=""
DESCRIPTION="Configuring accessibility options..."
db_get passwd/username
TARGET_USERNAME="$RET"

copy_orca_config()
{
	mkdir -p /target/tmp/ugtr-a11y-dconf.d
	sudo -u $USERNAME /usr/bin/dconf dump /org/gnome/orca/ > /home/$USERNAME/01-orca-settings
	cp /home/$USERNAME/01-orca-settings /target/tmp/user-a11y-dconf.d
	mv /home/$USERNAME/01-orca-settings /target/tmp/ugtr-a11y-dconf.d
	chroot /target /usr/bin/dconf compile /tmp/dconf.lightdm /tmp/ugtr-a11y-dconf.d
	mkdir -p /target/var/lib/lightdm/.config/dconf
	mv /target/tmp/dconf.lightdm /target/var/lib/lightdm/.config/dconf/user
	chroot /target chown lightdm.lightdm -R /var/lib/lightdm/.config
	rm -r /target/tmp/ugtr-a11y-dconf.d
}

# Args: $1 - The profile name
setup_profile()
{
	if [ -d /target/usr/share/a11y-profile-manager/profiles/$1 ] &&
	   [ -x /usr/bin/a11y-profile-manager ] &&
	   [ -x /usr/bin/dconf ] &&
	   [ -x /target/usr/bin/dconf ]; then
		mkdir -p /target/tmp/user-a11y-dconf.d
		/usr/bin/a11y-profile-manager -s $1 -D /tmp/user-a11y-dconf.d/01-profile
		chroot /target /usr/bin/dconf compile /tmp/dconf.$TARGET_USERNAME /tmp/user-a11y-dconf.d
		mkdir -p /target/home/$TARGET_USERNAME/.config/dconf
		mv /target/tmp/dconf.$TARGET_USERNAME /target/home/$TARGET_USERNAME/.config/dconf/user
		chroot /target chown $TARGET_USERNAME.$TARGET_USERNAME -R /home/$TARGET_USERNAME/.config
		rm -r /target/tmp/user-a11y-dconf.d
	fi
}

for x in $(cat /proc/cmdline); do
	case $x in
		# Lesser Visual Impairment
		access=v1)
			setup_profile high-contrast
			exit
                        ;;
		# Moderate Visual Impairment
		access=v2)
			setup_profile magnifier
			exit
                        ;;
		# Blindness
		access=v3)
			setup_profile blindness
			copy_orca_config
			exit
                        ;;
		# Braille
		braille=ask)
			setup_profile braille
			copy_orca_config
			exit
                        ;;
		# Minor Motor Difficulties
		access=m1)
			setup_profile keyboard-modifiers
			exit
                        ;;
		# Motor Difficulties - pointing devices
		access=m2)
			setup_profile onscreen-keyboard
			exit
                        ;;
		esac
done

# Check the live user GSettings for the active profile if any.
A11Y_PROFILE="$(sudo -u $USERNAME gsettings get com.canonical.a11y-profile-manager active-profile)"

case "$A11Y_PROFILE" in
	# Lesser Visual Impairment
	high-contrast)
		setup_profile high-contrast
		exit
		;;
	# Moderate Visual Impairment
	magnifier)
		setup_profile magnifier
		exit
		;;
	# Blindness
	screen-reader)
		copy_orca_config
		setup_profile screen-reader
		exit
		;;
	# Braille
	braille)
		copy_orca_config
		setup_profile braille
		exit
		;;
	# Minor Motor Difficulties
	keyboard-modifiers)
		setup_profile keyboard-modifiers
		exit
		;;
	# Motor Difficulties - pointing devices
	onscreen-keyboard)
		setup_profile onscreen-keyboard
		exit
		;;
esac

