#!/bin/sh

set -e
exec 2>&1
set -x

cd "$AUTOPKGTEST_TMP"


if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

echo "1..1"

cat > trivial.c <<'EOF'
#include <stdio.h>

#include <flatpak/flatpak.h>

int main (void)
{
  flatpak_error_quark ();
  g_print ("ok 1\n");
  return 0;
}
EOF

# Deliberately word-splitting, that's how pkg-config works:
# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -o trivial trivial.c $("${CROSS_COMPILE}pkg-config" --cflags --libs flatpak)
test -x trivial
./trivial
