#!/bin/sh

set -e
exec 2>&1
set -x

cd "$AUTOPKGTEST_TMP"

echo "1..1"

cat > trivial.c <<'EOF'
#include <stdio.h>

#include <flatpak/flatpak.h>

int main (void)
{
  flatpak_error_quark ();
  g_print ("ok 1\n");
  return 0;
}
EOF

gcc -o trivial trivial.c $(pkg-config --cflags --libs flatpak)
test -x trivial
./trivial
