#!/bin/sh
# autopkgtest check: Build the data cache, ensure no errors happen while doing that.
# (c) 2015 Matthias Klumpp <mak@debian.org>
set -e

export G_DEBUG=fatal-warnings

appstreamcli refresh-cache --force --verbose

echo "run: OK"
