#!/bin/bash

unset bad
for x in $(py3versions -s); do
    printf "%s testing...\n" "$x"
    script='import gpg; c = gpg.Context()'
    if "$x" -c "$script"; then
        printf "%s OK\n" "$x"
    else
        printf "%s FAILED\n" "$x" >&2
        bad=true
    fi
done

if [ "$bad" = true ]; then
    exit 1
else
    exit 0
fi
