/*
 * Generated by gdbus-codegen 2.46.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "gsd-screen-saver-glue.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gnome.ScreenSaver
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:GsdScreenSaver
 * @title: GsdScreenSaver
 * @short_description: Generated C code for the org.gnome.ScreenSaver D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gnome.ScreenSaver ---- */

static const _ExtendedGDBusMethodInfo _gsd_screen_saver_method_info_lock =
{
  {
    -1,
    (gchar *) "Lock",
    NULL,
    NULL,
    NULL
  },
  "handle-lock",
  FALSE
};

static const _ExtendedGDBusArgInfo _gsd_screen_saver_method_info_get_active_OUT_ARG_active =
{
  {
    -1,
    (gchar *) "active",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_screen_saver_method_info_get_active_OUT_ARG_pointers[] =
{
  &_gsd_screen_saver_method_info_get_active_OUT_ARG_active,
  NULL
};

static const _ExtendedGDBusMethodInfo _gsd_screen_saver_method_info_get_active =
{
  {
    -1,
    (gchar *) "GetActive",
    NULL,
    (GDBusArgInfo **) &_gsd_screen_saver_method_info_get_active_OUT_ARG_pointers,
    NULL
  },
  "handle-get-active",
  FALSE
};

static const _ExtendedGDBusArgInfo _gsd_screen_saver_method_info_set_active_IN_ARG_value =
{
  {
    -1,
    (gchar *) "value",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_screen_saver_method_info_set_active_IN_ARG_pointers[] =
{
  &_gsd_screen_saver_method_info_set_active_IN_ARG_value,
  NULL
};

static const _ExtendedGDBusMethodInfo _gsd_screen_saver_method_info_set_active =
{
  {
    -1,
    (gchar *) "SetActive",
    (GDBusArgInfo **) &_gsd_screen_saver_method_info_set_active_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-active",
  FALSE
};

static const _ExtendedGDBusArgInfo _gsd_screen_saver_method_info_get_active_time_OUT_ARG_value =
{
  {
    -1,
    (gchar *) "value",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_screen_saver_method_info_get_active_time_OUT_ARG_pointers[] =
{
  &_gsd_screen_saver_method_info_get_active_time_OUT_ARG_value,
  NULL
};

static const _ExtendedGDBusMethodInfo _gsd_screen_saver_method_info_get_active_time =
{
  {
    -1,
    (gchar *) "GetActiveTime",
    NULL,
    (GDBusArgInfo **) &_gsd_screen_saver_method_info_get_active_time_OUT_ARG_pointers,
    NULL
  },
  "handle-get-active-time",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _gsd_screen_saver_method_info_pointers[] =
{
  &_gsd_screen_saver_method_info_lock,
  &_gsd_screen_saver_method_info_get_active,
  &_gsd_screen_saver_method_info_set_active,
  &_gsd_screen_saver_method_info_get_active_time,
  NULL
};

static const _ExtendedGDBusArgInfo _gsd_screen_saver_signal_info_active_changed_ARG_new_value =
{
  {
    -1,
    (gchar *) "new_value",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_screen_saver_signal_info_active_changed_ARG_pointers[] =
{
  &_gsd_screen_saver_signal_info_active_changed_ARG_new_value,
  NULL
};

static const _ExtendedGDBusSignalInfo _gsd_screen_saver_signal_info_active_changed =
{
  {
    -1,
    (gchar *) "ActiveChanged",
    (GDBusArgInfo **) &_gsd_screen_saver_signal_info_active_changed_ARG_pointers,
    NULL
  },
  "active-changed"
};

static const _ExtendedGDBusSignalInfo * const _gsd_screen_saver_signal_info_pointers[] =
{
  &_gsd_screen_saver_signal_info_active_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gsd_screen_saver_interface_info =
{
  {
    -1,
    (gchar *) "org.gnome.ScreenSaver",
    (GDBusMethodInfo **) &_gsd_screen_saver_method_info_pointers,
    (GDBusSignalInfo **) &_gsd_screen_saver_signal_info_pointers,
    NULL,
    NULL
  },
  "screen-saver",
};


/**
 * gsd_screen_saver_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gsd_screen_saver_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gsd_screen_saver_interface_info.parent_struct;
}

/**
 * gsd_screen_saver_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #GsdScreenSaver interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gsd_screen_saver_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * GsdScreenSaver:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>.
 */

/**
 * GsdScreenSaverIface:
 * @parent_iface: The parent interface.
 * @handle_get_active: Handler for the #GsdScreenSaver::handle-get-active signal.
 * @handle_get_active_time: Handler for the #GsdScreenSaver::handle-get-active-time signal.
 * @handle_lock: Handler for the #GsdScreenSaver::handle-lock signal.
 * @handle_set_active: Handler for the #GsdScreenSaver::handle-set-active signal.
 * @active_changed: Handler for the #GsdScreenSaver::active-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>.
 */

typedef GsdScreenSaverIface GsdScreenSaverInterface;
G_DEFINE_INTERFACE (GsdScreenSaver, gsd_screen_saver, G_TYPE_OBJECT);

static void
gsd_screen_saver_default_init (GsdScreenSaverIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * GsdScreenSaver::handle-lock:
   * @object: A #GsdScreenSaver.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-ScreenSaver.Lock">Lock()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_screen_saver_complete_lock() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-lock",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdScreenSaverIface, handle_lock),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GsdScreenSaver::handle-get-active:
   * @object: A #GsdScreenSaver.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActive">GetActive()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_screen_saver_complete_get_active() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-active",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdScreenSaverIface, handle_get_active),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GsdScreenSaver::handle-set-active:
   * @object: A #GsdScreenSaver.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_value: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-ScreenSaver.SetActive">SetActive()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_screen_saver_complete_set_active() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-active",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdScreenSaverIface, handle_set_active),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN);

  /**
   * GsdScreenSaver::handle-get-active-time:
   * @object: A #GsdScreenSaver.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActiveTime">GetActiveTime()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_screen_saver_complete_get_active_time() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-active-time",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdScreenSaverIface, handle_get_active_time),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject signals for received D-Bus signals: */
  /**
   * GsdScreenSaver::active-changed:
   * @object: A #GsdScreenSaver.
   * @arg_new_value: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gnome-ScreenSaver.ActiveChanged">"ActiveChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("active-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdScreenSaverIface, active_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_BOOLEAN);

}

/**
 * gsd_screen_saver_emit_active_changed:
 * @object: A #GsdScreenSaver.
 * @arg_new_value: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gnome-ScreenSaver.ActiveChanged">"ActiveChanged"</link> D-Bus signal.
 */
void
gsd_screen_saver_emit_active_changed (
    GsdScreenSaver *object,
    gboolean arg_new_value)
{
  g_signal_emit_by_name (object, "active-changed", arg_new_value);
}

/**
 * gsd_screen_saver_call_lock:
 * @proxy: A #GsdScreenSaverProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.Lock">Lock()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_screen_saver_call_lock_finish() to get the result of the operation.
 *
 * See gsd_screen_saver_call_lock_sync() for the synchronous, blocking version of this method.
 */
void
gsd_screen_saver_call_lock (
    GsdScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Lock",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_screen_saver_call_lock_finish:
 * @proxy: A #GsdScreenSaverProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_screen_saver_call_lock().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_screen_saver_call_lock().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_lock_finish (
    GsdScreenSaver *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_lock_sync:
 * @proxy: A #GsdScreenSaverProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.Lock">Lock()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_screen_saver_call_lock() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_lock_sync (
    GsdScreenSaver *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Lock",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_get_active:
 * @proxy: A #GsdScreenSaverProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActive">GetActive()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_screen_saver_call_get_active_finish() to get the result of the operation.
 *
 * See gsd_screen_saver_call_get_active_sync() for the synchronous, blocking version of this method.
 */
void
gsd_screen_saver_call_get_active (
    GsdScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetActive",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_screen_saver_call_get_active_finish:
 * @proxy: A #GsdScreenSaverProxy.
 * @out_active: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_screen_saver_call_get_active().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_screen_saver_call_get_active().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_get_active_finish (
    GsdScreenSaver *proxy,
    gboolean *out_active,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_active);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_get_active_sync:
 * @proxy: A #GsdScreenSaverProxy.
 * @out_active: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActive">GetActive()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_screen_saver_call_get_active() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_get_active_sync (
    GsdScreenSaver *proxy,
    gboolean *out_active,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetActive",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_active);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_set_active:
 * @proxy: A #GsdScreenSaverProxy.
 * @arg_value: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.SetActive">SetActive()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_screen_saver_call_set_active_finish() to get the result of the operation.
 *
 * See gsd_screen_saver_call_set_active_sync() for the synchronous, blocking version of this method.
 */
void
gsd_screen_saver_call_set_active (
    GsdScreenSaver *proxy,
    gboolean arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetActive",
    g_variant_new ("(b)",
                   arg_value),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_screen_saver_call_set_active_finish:
 * @proxy: A #GsdScreenSaverProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_screen_saver_call_set_active().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_screen_saver_call_set_active().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_set_active_finish (
    GsdScreenSaver *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_set_active_sync:
 * @proxy: A #GsdScreenSaverProxy.
 * @arg_value: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.SetActive">SetActive()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_screen_saver_call_set_active() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_set_active_sync (
    GsdScreenSaver *proxy,
    gboolean arg_value,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetActive",
    g_variant_new ("(b)",
                   arg_value),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_get_active_time:
 * @proxy: A #GsdScreenSaverProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActiveTime">GetActiveTime()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_screen_saver_call_get_active_time_finish() to get the result of the operation.
 *
 * See gsd_screen_saver_call_get_active_time_sync() for the synchronous, blocking version of this method.
 */
void
gsd_screen_saver_call_get_active_time (
    GsdScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetActiveTime",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_screen_saver_call_get_active_time_finish:
 * @proxy: A #GsdScreenSaverProxy.
 * @out_value: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_screen_saver_call_get_active_time().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_screen_saver_call_get_active_time().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_get_active_time_finish (
    GsdScreenSaver *proxy,
    guint *out_value,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_value);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_call_get_active_time_sync:
 * @proxy: A #GsdScreenSaverProxy.
 * @out_value: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActiveTime">GetActiveTime()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_screen_saver_call_get_active_time() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_screen_saver_call_get_active_time_sync (
    GsdScreenSaver *proxy,
    guint *out_value,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetActiveTime",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_value);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_screen_saver_complete_lock:
 * @object: A #GsdScreenSaver.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-ScreenSaver.Lock">Lock()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_screen_saver_complete_lock (
    GsdScreenSaver *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gsd_screen_saver_complete_get_active:
 * @object: A #GsdScreenSaver.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @active: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActive">GetActive()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_screen_saver_complete_get_active (
    GsdScreenSaver *object,
    GDBusMethodInvocation *invocation,
    gboolean active)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   active));
}

/**
 * gsd_screen_saver_complete_set_active:
 * @object: A #GsdScreenSaver.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-ScreenSaver.SetActive">SetActive()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_screen_saver_complete_set_active (
    GsdScreenSaver *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gsd_screen_saver_complete_get_active_time:
 * @object: A #GsdScreenSaver.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @value: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-ScreenSaver.GetActiveTime">GetActiveTime()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_screen_saver_complete_get_active_time (
    GsdScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint value)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   value));
}

/* ------------------------------------------------------------------------ */

/**
 * GsdScreenSaverProxy:
 *
 * The #GsdScreenSaverProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GsdScreenSaverProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GsdScreenSaverProxy.
 */

struct _GsdScreenSaverProxyPrivate
{
  GData *qdata;
};

static void gsd_screen_saver_proxy_iface_init (GsdScreenSaverIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GsdScreenSaverProxy, gsd_screen_saver_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (GsdScreenSaverProxy)
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SCREEN_SAVER, gsd_screen_saver_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (GsdScreenSaverProxy, gsd_screen_saver_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SCREEN_SAVER, gsd_screen_saver_proxy_iface_init));

#endif
static void
gsd_screen_saver_proxy_finalize (GObject *object)
{
  GsdScreenSaverProxy *proxy = GSD_SCREEN_SAVER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gsd_screen_saver_proxy_parent_class)->finalize (object);
}

static void
gsd_screen_saver_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
gsd_screen_saver_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
gsd_screen_saver_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gsd_screen_saver_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GSD_TYPE_SCREEN_SAVER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GSD_TYPE_SCREEN_SAVER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gsd_screen_saver_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GsdScreenSaverProxy *proxy = GSD_SCREEN_SAVER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_screen_saver_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_screen_saver_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
gsd_screen_saver_proxy_init (GsdScreenSaverProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = gsd_screen_saver_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GSD_TYPE_SCREEN_SAVER_PROXY, GsdScreenSaverProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gsd_screen_saver_interface_info ());
}

static void
gsd_screen_saver_proxy_class_init (GsdScreenSaverProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gsd_screen_saver_proxy_finalize;
  gobject_class->get_property = gsd_screen_saver_proxy_get_property;
  gobject_class->set_property = gsd_screen_saver_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gsd_screen_saver_proxy_g_signal;
  proxy_class->g_properties_changed = gsd_screen_saver_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GsdScreenSaverProxyPrivate));
#endif
}

static void
gsd_screen_saver_proxy_iface_init (GsdScreenSaverIface *iface)
{
}

/**
 * gsd_screen_saver_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_screen_saver_proxy_new_finish() to get the result of the operation.
 *
 * See gsd_screen_saver_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gsd_screen_saver_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GSD_TYPE_SCREEN_SAVER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
}

/**
 * gsd_screen_saver_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_screen_saver_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gsd_screen_saver_proxy_new().
 *
 * Returns: (transfer full) (type GsdScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdScreenSaver *
gsd_screen_saver_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GSD_SCREEN_SAVER (ret);
  else
    return NULL;
}

/**
 * gsd_screen_saver_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gsd_screen_saver_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GsdScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdScreenSaver *
gsd_screen_saver_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GSD_TYPE_SCREEN_SAVER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
  if (ret != NULL)
    return GSD_SCREEN_SAVER (ret);
  else
    return NULL;
}


/**
 * gsd_screen_saver_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gsd_screen_saver_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_screen_saver_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gsd_screen_saver_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gsd_screen_saver_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GSD_TYPE_SCREEN_SAVER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
}

/**
 * gsd_screen_saver_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_screen_saver_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gsd_screen_saver_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GsdScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdScreenSaver *
gsd_screen_saver_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GSD_SCREEN_SAVER (ret);
  else
    return NULL;
}

/**
 * gsd_screen_saver_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gsd_screen_saver_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gsd_screen_saver_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GsdScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdScreenSaver *
gsd_screen_saver_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GSD_TYPE_SCREEN_SAVER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
  if (ret != NULL)
    return GSD_SCREEN_SAVER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GsdScreenSaverSkeleton:
 *
 * The #GsdScreenSaverSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GsdScreenSaverSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GsdScreenSaverSkeleton.
 */

struct _GsdScreenSaverSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gsd_screen_saver_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GsdScreenSaverSkeleton *skeleton = GSD_SCREEN_SAVER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GSD_TYPE_SCREEN_SAVER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GSD_TYPE_SCREEN_SAVER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gsd_screen_saver_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GsdScreenSaverSkeleton *skeleton = GSD_SCREEN_SAVER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_screen_saver_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gsd_screen_saver_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GsdScreenSaverSkeleton *skeleton = GSD_SCREEN_SAVER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_screen_saver_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gsd_screen_saver_skeleton_vtable =
{
  _gsd_screen_saver_skeleton_handle_method_call,
  _gsd_screen_saver_skeleton_handle_get_property,
  _gsd_screen_saver_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
gsd_screen_saver_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return gsd_screen_saver_interface_info ();
}

static GDBusInterfaceVTable *
gsd_screen_saver_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_gsd_screen_saver_skeleton_vtable;
}

static GVariant *
gsd_screen_saver_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GsdScreenSaverSkeleton *skeleton = GSD_SCREEN_SAVER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gsd_screen_saver_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gsd_screen_saver_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gsd_screen_saver_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gsd_screen_saver_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.ScreenSaver", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
gsd_screen_saver_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_gsd_screen_saver_on_signal_active_changed (
    GsdScreenSaver *object,
    gboolean arg_new_value)
{
  GsdScreenSaverSkeleton *skeleton = GSD_SCREEN_SAVER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(b)",
                   arg_new_value));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.ScreenSaver", "ActiveChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void gsd_screen_saver_skeleton_iface_init (GsdScreenSaverIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GsdScreenSaverSkeleton, gsd_screen_saver_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (GsdScreenSaverSkeleton)
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SCREEN_SAVER, gsd_screen_saver_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (GsdScreenSaverSkeleton, gsd_screen_saver_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SCREEN_SAVER, gsd_screen_saver_skeleton_iface_init));

#endif
static void
gsd_screen_saver_skeleton_finalize (GObject *object)
{
  GsdScreenSaverSkeleton *skeleton = GSD_SCREEN_SAVER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gsd_screen_saver_skeleton_parent_class)->finalize (object);
}

static void
gsd_screen_saver_skeleton_init (GsdScreenSaverSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = gsd_screen_saver_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GSD_TYPE_SCREEN_SAVER_SKELETON, GsdScreenSaverSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
gsd_screen_saver_skeleton_class_init (GsdScreenSaverSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gsd_screen_saver_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gsd_screen_saver_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gsd_screen_saver_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gsd_screen_saver_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gsd_screen_saver_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GsdScreenSaverSkeletonPrivate));
#endif
}

static void
gsd_screen_saver_skeleton_iface_init (GsdScreenSaverIface *iface)
{
  iface->active_changed = _gsd_screen_saver_on_signal_active_changed;
}

/**
 * gsd_screen_saver_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>.
 *
 * Returns: (transfer full) (type GsdScreenSaverSkeleton): The skeleton object.
 */
GsdScreenSaver *
gsd_screen_saver_skeleton_new (void)
{
  return GSD_SCREEN_SAVER (g_object_new (GSD_TYPE_SCREEN_SAVER_SKELETON, NULL));
}

