/*
 * Generated by gdbus-codegen 2.36.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "shell-key-grabber.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gnome.Shell
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:ShellKeyGrabber
 * @title: ShellKeyGrabber
 * @short_description: Generated C code for the org.gnome.Shell D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gnome.Shell ---- */

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_grab_accelerator_IN_ARG_accelerator =
{
  {
    -1,
    (gchar *) "accelerator",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_grab_accelerator_IN_ARG_flags =
{
  {
    -1,
    (gchar *) "flags",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_method_info_grab_accelerator_IN_ARG_pointers[] =
{
  &_shell_key_grabber_method_info_grab_accelerator_IN_ARG_accelerator,
  &_shell_key_grabber_method_info_grab_accelerator_IN_ARG_flags,
  NULL
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_grab_accelerator_OUT_ARG_action =
{
  {
    -1,
    (gchar *) "action",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_method_info_grab_accelerator_OUT_ARG_pointers[] =
{
  &_shell_key_grabber_method_info_grab_accelerator_OUT_ARG_action,
  NULL
};

static const _ExtendedGDBusMethodInfo _shell_key_grabber_method_info_grab_accelerator =
{
  {
    -1,
    (gchar *) "GrabAccelerator",
    (GDBusArgInfo **) &_shell_key_grabber_method_info_grab_accelerator_IN_ARG_pointers,
    (GDBusArgInfo **) &_shell_key_grabber_method_info_grab_accelerator_OUT_ARG_pointers,
    NULL
  },
  "handle-grab-accelerator",
  FALSE
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_grab_accelerators_IN_ARG_accelerators =
{
  {
    -1,
    (gchar *) "accelerators",
    (gchar *) "a(su)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_method_info_grab_accelerators_IN_ARG_pointers[] =
{
  &_shell_key_grabber_method_info_grab_accelerators_IN_ARG_accelerators,
  NULL
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_grab_accelerators_OUT_ARG_actions =
{
  {
    -1,
    (gchar *) "actions",
    (gchar *) "au",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_method_info_grab_accelerators_OUT_ARG_pointers[] =
{
  &_shell_key_grabber_method_info_grab_accelerators_OUT_ARG_actions,
  NULL
};

static const _ExtendedGDBusMethodInfo _shell_key_grabber_method_info_grab_accelerators =
{
  {
    -1,
    (gchar *) "GrabAccelerators",
    (GDBusArgInfo **) &_shell_key_grabber_method_info_grab_accelerators_IN_ARG_pointers,
    (GDBusArgInfo **) &_shell_key_grabber_method_info_grab_accelerators_OUT_ARG_pointers,
    NULL
  },
  "handle-grab-accelerators",
  FALSE
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_ungrab_accelerator_IN_ARG_action =
{
  {
    -1,
    (gchar *) "action",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_method_info_ungrab_accelerator_IN_ARG_pointers[] =
{
  &_shell_key_grabber_method_info_ungrab_accelerator_IN_ARG_action,
  NULL
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_method_info_ungrab_accelerator_OUT_ARG_success =
{
  {
    -1,
    (gchar *) "success",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_method_info_ungrab_accelerator_OUT_ARG_pointers[] =
{
  &_shell_key_grabber_method_info_ungrab_accelerator_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _shell_key_grabber_method_info_ungrab_accelerator =
{
  {
    -1,
    (gchar *) "UngrabAccelerator",
    (GDBusArgInfo **) &_shell_key_grabber_method_info_ungrab_accelerator_IN_ARG_pointers,
    (GDBusArgInfo **) &_shell_key_grabber_method_info_ungrab_accelerator_OUT_ARG_pointers,
    NULL
  },
  "handle-ungrab-accelerator",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _shell_key_grabber_method_info_pointers[] =
{
  &_shell_key_grabber_method_info_grab_accelerator,
  &_shell_key_grabber_method_info_grab_accelerators,
  &_shell_key_grabber_method_info_ungrab_accelerator,
  NULL
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_signal_info_accelerator_activated_ARG_action =
{
  {
    -1,
    (gchar *) "action",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _shell_key_grabber_signal_info_accelerator_activated_ARG_device =
{
  {
    -1,
    (gchar *) "device",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _shell_key_grabber_signal_info_accelerator_activated_ARG_pointers[] =
{
  &_shell_key_grabber_signal_info_accelerator_activated_ARG_action,
  &_shell_key_grabber_signal_info_accelerator_activated_ARG_device,
  NULL
};

static const _ExtendedGDBusSignalInfo _shell_key_grabber_signal_info_accelerator_activated =
{
  {
    -1,
    (gchar *) "AcceleratorActivated",
    (GDBusArgInfo **) &_shell_key_grabber_signal_info_accelerator_activated_ARG_pointers,
    NULL
  },
  "accelerator-activated"
};

static const _ExtendedGDBusSignalInfo * const _shell_key_grabber_signal_info_pointers[] =
{
  &_shell_key_grabber_signal_info_accelerator_activated,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _shell_key_grabber_interface_info =
{
  {
    -1,
    (gchar *) "org.gnome.Shell",
    (GDBusMethodInfo **) &_shell_key_grabber_method_info_pointers,
    (GDBusSignalInfo **) &_shell_key_grabber_signal_info_pointers,
    NULL,
    NULL
  },
  "key-grabber",
};


/**
 * shell_key_grabber_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
shell_key_grabber_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_shell_key_grabber_interface_info.parent_struct;
}

/**
 * shell_key_grabber_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #ShellKeyGrabber interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
shell_key_grabber_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * ShellKeyGrabber:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link>.
 */

/**
 * ShellKeyGrabberIface:
 * @parent_iface: The parent interface.
 * @handle_grab_accelerator: Handler for the #ShellKeyGrabber::handle-grab-accelerator signal.
 * @handle_grab_accelerators: Handler for the #ShellKeyGrabber::handle-grab-accelerators signal.
 * @handle_ungrab_accelerator: Handler for the #ShellKeyGrabber::handle-ungrab-accelerator signal.
 * @accelerator_activated: Handler for the #ShellKeyGrabber::accelerator-activated signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link>.
 */

static void
shell_key_grabber_default_init (ShellKeyGrabberIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * ShellKeyGrabber::handle-grab-accelerator:
   * @object: A #ShellKeyGrabber.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_accelerator: Argument passed by remote caller.
   * @arg_flags: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerator">GrabAccelerator()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call shell_key_grabber_complete_grab_accelerator() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-grab-accelerator",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ShellKeyGrabberIface, handle_grab_accelerator),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_UINT);

  /**
   * ShellKeyGrabber::handle-grab-accelerators:
   * @object: A #ShellKeyGrabber.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_accelerators: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerators">GrabAccelerators()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call shell_key_grabber_complete_grab_accelerators() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-grab-accelerators",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ShellKeyGrabberIface, handle_grab_accelerators),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /**
   * ShellKeyGrabber::handle-ungrab-accelerator:
   * @object: A #ShellKeyGrabber.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_action: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-Shell.UngrabAccelerator">UngrabAccelerator()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call shell_key_grabber_complete_ungrab_accelerator() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-ungrab-accelerator",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ShellKeyGrabberIface, handle_ungrab_accelerator),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /* GObject signals for received D-Bus signals: */
  /**
   * ShellKeyGrabber::accelerator-activated:
   * @object: A #ShellKeyGrabber.
   * @arg_action: Argument.
   * @arg_device: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gnome-Shell.AcceleratorActivated">"AcceleratorActivated"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("accelerator-activated",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ShellKeyGrabberIface, accelerator_activated),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_UINT, G_TYPE_UINT);

}

typedef ShellKeyGrabberIface ShellKeyGrabberInterface;
G_DEFINE_INTERFACE (ShellKeyGrabber, shell_key_grabber, G_TYPE_OBJECT);

/**
 * shell_key_grabber_emit_accelerator_activated:
 * @object: A #ShellKeyGrabber.
 * @arg_action: Argument to pass with the signal.
 * @arg_device: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gnome-Shell.AcceleratorActivated">"AcceleratorActivated"</link> D-Bus signal.
 */
void
shell_key_grabber_emit_accelerator_activated (
    ShellKeyGrabber *object,
    guint arg_action,
    guint arg_device)
{
  g_signal_emit_by_name (object, "accelerator-activated", arg_action, arg_device);
}

/**
 * shell_key_grabber_call_grab_accelerator:
 * @proxy: A #ShellKeyGrabberProxy.
 * @arg_accelerator: Argument to pass with the method invocation.
 * @arg_flags: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerator">GrabAccelerator()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call shell_key_grabber_call_grab_accelerator_finish() to get the result of the operation.
 *
 * See shell_key_grabber_call_grab_accelerator_sync() for the synchronous, blocking version of this method.
 */
void
shell_key_grabber_call_grab_accelerator (
    ShellKeyGrabber *proxy,
    const gchar *arg_accelerator,
    guint arg_flags,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GrabAccelerator",
    g_variant_new ("(su)",
                   arg_accelerator,
                   arg_flags),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * shell_key_grabber_call_grab_accelerator_finish:
 * @proxy: A #ShellKeyGrabberProxy.
 * @out_action: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to shell_key_grabber_call_grab_accelerator().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with shell_key_grabber_call_grab_accelerator().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
shell_key_grabber_call_grab_accelerator_finish (
    ShellKeyGrabber *proxy,
    guint *out_action,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_action);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * shell_key_grabber_call_grab_accelerator_sync:
 * @proxy: A #ShellKeyGrabberProxy.
 * @arg_accelerator: Argument to pass with the method invocation.
 * @arg_flags: Argument to pass with the method invocation.
 * @out_action: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerator">GrabAccelerator()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See shell_key_grabber_call_grab_accelerator() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
shell_key_grabber_call_grab_accelerator_sync (
    ShellKeyGrabber *proxy,
    const gchar *arg_accelerator,
    guint arg_flags,
    guint *out_action,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GrabAccelerator",
    g_variant_new ("(su)",
                   arg_accelerator,
                   arg_flags),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_action);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * shell_key_grabber_call_grab_accelerators:
 * @proxy: A #ShellKeyGrabberProxy.
 * @arg_accelerators: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerators">GrabAccelerators()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call shell_key_grabber_call_grab_accelerators_finish() to get the result of the operation.
 *
 * See shell_key_grabber_call_grab_accelerators_sync() for the synchronous, blocking version of this method.
 */
void
shell_key_grabber_call_grab_accelerators (
    ShellKeyGrabber *proxy,
    GVariant *arg_accelerators,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GrabAccelerators",
    g_variant_new ("(@a(su))",
                   arg_accelerators),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * shell_key_grabber_call_grab_accelerators_finish:
 * @proxy: A #ShellKeyGrabberProxy.
 * @out_actions: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to shell_key_grabber_call_grab_accelerators().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with shell_key_grabber_call_grab_accelerators().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
shell_key_grabber_call_grab_accelerators_finish (
    ShellKeyGrabber *proxy,
    GVariant **out_actions,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@au)",
                 out_actions);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * shell_key_grabber_call_grab_accelerators_sync:
 * @proxy: A #ShellKeyGrabberProxy.
 * @arg_accelerators: Argument to pass with the method invocation.
 * @out_actions: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerators">GrabAccelerators()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See shell_key_grabber_call_grab_accelerators() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
shell_key_grabber_call_grab_accelerators_sync (
    ShellKeyGrabber *proxy,
    GVariant *arg_accelerators,
    GVariant **out_actions,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GrabAccelerators",
    g_variant_new ("(@a(su))",
                   arg_accelerators),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@au)",
                 out_actions);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * shell_key_grabber_call_ungrab_accelerator:
 * @proxy: A #ShellKeyGrabberProxy.
 * @arg_action: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-Shell.UngrabAccelerator">UngrabAccelerator()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call shell_key_grabber_call_ungrab_accelerator_finish() to get the result of the operation.
 *
 * See shell_key_grabber_call_ungrab_accelerator_sync() for the synchronous, blocking version of this method.
 */
void
shell_key_grabber_call_ungrab_accelerator (
    ShellKeyGrabber *proxy,
    guint arg_action,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "UngrabAccelerator",
    g_variant_new ("(u)",
                   arg_action),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * shell_key_grabber_call_ungrab_accelerator_finish:
 * @proxy: A #ShellKeyGrabberProxy.
 * @out_success: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to shell_key_grabber_call_ungrab_accelerator().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with shell_key_grabber_call_ungrab_accelerator().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
shell_key_grabber_call_ungrab_accelerator_finish (
    ShellKeyGrabber *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * shell_key_grabber_call_ungrab_accelerator_sync:
 * @proxy: A #ShellKeyGrabberProxy.
 * @arg_action: Argument to pass with the method invocation.
 * @out_success: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-Shell.UngrabAccelerator">UngrabAccelerator()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See shell_key_grabber_call_ungrab_accelerator() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
shell_key_grabber_call_ungrab_accelerator_sync (
    ShellKeyGrabber *proxy,
    guint arg_action,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "UngrabAccelerator",
    g_variant_new ("(u)",
                   arg_action),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * shell_key_grabber_complete_grab_accelerator:
 * @object: A #ShellKeyGrabber.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @action: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerator">GrabAccelerator()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
shell_key_grabber_complete_grab_accelerator (
    ShellKeyGrabber *object,
    GDBusMethodInvocation *invocation,
    guint action)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   action));
}

/**
 * shell_key_grabber_complete_grab_accelerators:
 * @object: A #ShellKeyGrabber.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @actions: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-Shell.GrabAccelerators">GrabAccelerators()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
shell_key_grabber_complete_grab_accelerators (
    ShellKeyGrabber *object,
    GDBusMethodInvocation *invocation,
    GVariant *actions)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@au)",
                   actions));
}

/**
 * shell_key_grabber_complete_ungrab_accelerator:
 * @object: A #ShellKeyGrabber.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @success: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-Shell.UngrabAccelerator">UngrabAccelerator()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
shell_key_grabber_complete_ungrab_accelerator (
    ShellKeyGrabber *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

/* ------------------------------------------------------------------------ */

/**
 * ShellKeyGrabberProxy:
 *
 * The #ShellKeyGrabberProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ShellKeyGrabberProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ShellKeyGrabberProxy.
 */

struct _ShellKeyGrabberProxyPrivate
{
  GData *qdata;
};

static void shell_key_grabber_proxy_iface_init (ShellKeyGrabberIface *iface);

G_DEFINE_TYPE_WITH_CODE (ShellKeyGrabberProxy, shell_key_grabber_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (SHELL_TYPE_KEY_GRABBER, shell_key_grabber_proxy_iface_init));

static void
shell_key_grabber_proxy_finalize (GObject *object)
{
  ShellKeyGrabberProxy *proxy = SHELL_KEY_GRABBER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (shell_key_grabber_proxy_parent_class)->finalize (object);
}

static void
shell_key_grabber_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
shell_key_grabber_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
shell_key_grabber_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_shell_key_grabber_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], SHELL_TYPE_KEY_GRABBER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, SHELL_TYPE_KEY_GRABBER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
shell_key_grabber_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  ShellKeyGrabberProxy *proxy = SHELL_KEY_GRABBER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_shell_key_grabber_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_shell_key_grabber_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
shell_key_grabber_proxy_init (ShellKeyGrabberProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, SHELL_TYPE_KEY_GRABBER_PROXY, ShellKeyGrabberProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), shell_key_grabber_interface_info ());
}

static void
shell_key_grabber_proxy_class_init (ShellKeyGrabberProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (ShellKeyGrabberProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = shell_key_grabber_proxy_finalize;
  gobject_class->get_property = shell_key_grabber_proxy_get_property;
  gobject_class->set_property = shell_key_grabber_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = shell_key_grabber_proxy_g_signal;
  proxy_class->g_properties_changed = shell_key_grabber_proxy_g_properties_changed;

}

static void
shell_key_grabber_proxy_iface_init (ShellKeyGrabberIface *iface)
{
}

/**
 * shell_key_grabber_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call shell_key_grabber_proxy_new_finish() to get the result of the operation.
 *
 * See shell_key_grabber_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
shell_key_grabber_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (SHELL_TYPE_KEY_GRABBER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.Shell", NULL);
}

/**
 * shell_key_grabber_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to shell_key_grabber_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with shell_key_grabber_proxy_new().
 *
 * Returns: (transfer full) (type ShellKeyGrabberProxy): The constructed proxy object or %NULL if @error is set.
 */
ShellKeyGrabber *
shell_key_grabber_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SHELL_KEY_GRABBER (ret);
  else
    return NULL;
}

/**
 * shell_key_grabber_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See shell_key_grabber_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ShellKeyGrabberProxy): The constructed proxy object or %NULL if @error is set.
 */
ShellKeyGrabber *
shell_key_grabber_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (SHELL_TYPE_KEY_GRABBER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.Shell", NULL);
  if (ret != NULL)
    return SHELL_KEY_GRABBER (ret);
  else
    return NULL;
}


/**
 * shell_key_grabber_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like shell_key_grabber_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call shell_key_grabber_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See shell_key_grabber_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
shell_key_grabber_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (SHELL_TYPE_KEY_GRABBER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.Shell", NULL);
}

/**
 * shell_key_grabber_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to shell_key_grabber_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with shell_key_grabber_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type ShellKeyGrabberProxy): The constructed proxy object or %NULL if @error is set.
 */
ShellKeyGrabber *
shell_key_grabber_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SHELL_KEY_GRABBER (ret);
  else
    return NULL;
}

/**
 * shell_key_grabber_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like shell_key_grabber_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See shell_key_grabber_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ShellKeyGrabberProxy): The constructed proxy object or %NULL if @error is set.
 */
ShellKeyGrabber *
shell_key_grabber_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (SHELL_TYPE_KEY_GRABBER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.Shell", NULL);
  if (ret != NULL)
    return SHELL_KEY_GRABBER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * ShellKeyGrabberSkeleton:
 *
 * The #ShellKeyGrabberSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ShellKeyGrabberSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ShellKeyGrabberSkeleton.
 */

struct _ShellKeyGrabberSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_shell_key_grabber_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  ShellKeyGrabberSkeleton *skeleton = SHELL_KEY_GRABBER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], SHELL_TYPE_KEY_GRABBER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, SHELL_TYPE_KEY_GRABBER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_shell_key_grabber_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  ShellKeyGrabberSkeleton *skeleton = SHELL_KEY_GRABBER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_shell_key_grabber_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_shell_key_grabber_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  ShellKeyGrabberSkeleton *skeleton = SHELL_KEY_GRABBER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_shell_key_grabber_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _shell_key_grabber_skeleton_vtable =
{
  _shell_key_grabber_skeleton_handle_method_call,
  _shell_key_grabber_skeleton_handle_get_property,
  _shell_key_grabber_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
shell_key_grabber_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return shell_key_grabber_interface_info ();
}

static GDBusInterfaceVTable *
shell_key_grabber_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_shell_key_grabber_skeleton_vtable;
}

static GVariant *
shell_key_grabber_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  ShellKeyGrabberSkeleton *skeleton = SHELL_KEY_GRABBER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_shell_key_grabber_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _shell_key_grabber_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _shell_key_grabber_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _shell_key_grabber_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.Shell", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
shell_key_grabber_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_shell_key_grabber_on_signal_accelerator_activated (
    ShellKeyGrabber *object,
    guint arg_action,
    guint arg_device)
{
  ShellKeyGrabberSkeleton *skeleton = SHELL_KEY_GRABBER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(uu)",
                   arg_action,
                   arg_device));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.Shell", "AcceleratorActivated",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void shell_key_grabber_skeleton_iface_init (ShellKeyGrabberIface *iface);
G_DEFINE_TYPE_WITH_CODE (ShellKeyGrabberSkeleton, shell_key_grabber_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (SHELL_TYPE_KEY_GRABBER, shell_key_grabber_skeleton_iface_init));

static void
shell_key_grabber_skeleton_finalize (GObject *object)
{
  ShellKeyGrabberSkeleton *skeleton = SHELL_KEY_GRABBER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (shell_key_grabber_skeleton_parent_class)->finalize (object);
}

static void
shell_key_grabber_skeleton_init (ShellKeyGrabberSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, SHELL_TYPE_KEY_GRABBER_SKELETON, ShellKeyGrabberSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
shell_key_grabber_skeleton_class_init (ShellKeyGrabberSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (ShellKeyGrabberSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = shell_key_grabber_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = shell_key_grabber_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = shell_key_grabber_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = shell_key_grabber_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = shell_key_grabber_skeleton_dbus_interface_get_vtable;
}

static void
shell_key_grabber_skeleton_iface_init (ShellKeyGrabberIface *iface)
{
  iface->accelerator_activated = _shell_key_grabber_on_signal_accelerator_activated;
}

/**
 * shell_key_grabber_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gnome-Shell.top_of_page">org.gnome.Shell</link>.
 *
 * Returns: (transfer full) (type ShellKeyGrabberSkeleton): The skeleton object.
 */
ShellKeyGrabber *
shell_key_grabber_skeleton_new (void)
{
  return SHELL_KEY_GRABBER (g_object_new (SHELL_TYPE_KEY_GRABBER_SKELETON, NULL));
}

