#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling ibus-mozc auto setup..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# Not all users want to input Japanese. In a Japanese live session
# ibus-mozc is still enabled through gnome-settings-daemon.
mkdir -p /root/home/$USERNAME/.config
touch /root/home/$USERNAME/.config/ibus-mozc-gnome-initial-setup-done
chroot /root chown -R $USERNAME.$USERNAME /home/$USERNAME/.config

log_end_msg
