#! /bin/sh

PREREQ=""
DESCRIPTION="Set up the installer log directory for adm users..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

mkdir /root/var/log/installer
chmod 775 /root/var/log/installer
chroot /root chgrp adm /var/log/installer

log_end_msg
