#!/bin/sh

set -e

case "$1" in
    configure)
	# do it like udev and firmware-linux-*
	if [ -x /usr/sbin/update-initramfs ] && [ -e /etc/initramfs-tools/initramfs.conf ] ; then
	    update-initramfs -u
	else
	    echo "disable-intel-microcode: initramfs support missing" >&2
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
