usr/bin/dm-tool
usr/sbin/lightdm
usr/share/man
usr/share/locale
usr/share/help
usr/share/bash-completion
usr/share/polkit-1
usr/share/dbus-1
usr/share/accountsservice/
etc/apparmor.d/abstractions/lightdm
etc/apparmor.d/abstractions/lightdm_chromium-browser
etc/lightdm/users.conf
etc/lightdm/lightdm.conf
etc/lightdm/keys.conf
etc/apparmor.d/lightdm-guest-session
etc/pam.d
debian/01_debian.conf /etc/lightdm/lightdm.conf.d
debian/02_ubuntu.conf /etc/lightdm/lightdm.conf.d
usr/lib/*/lightdm/lightdm-guest-session
debian/lightdm.service /usr/lib/systemd/system/
debian/lightdm-session /usr/sbin
debian/lightdm-greeter-session /usr/lib/lightdm
debian/config-error-dialog.sh /usr/lib/lightdm
debian/source_lightdm.py /usr/share/apport/package-hooks
