debian/org.freedesktop.packagekit.pkla var/lib/polkit-1/localauthority/10-vendor.d/
etc/PackageKit/PackageKit.conf
etc/PackageKit/Vendor.conf
etc/apt/apt.conf.d/20packagekit
etc/dbus-1/system.d/org.freedesktop.PackageKit.conf
lib/systemd/system/*
usr/lib/*/packagekit-backend/*
usr/lib/packagekit/packagekit-direct
usr/lib/packagekit/packagekitd
usr/lib/packagekit/pk-offline-update
usr/share/PackageKit/helpers/aptcc/*
usr/share/PackageKit/helpers/test_spawn/*
usr/share/dbus-1/interfaces
usr/share/dbus-1/system-services/org.freedesktop.PackageKit.service
usr/share/locale/*/LC_MESSAGES/PackageKit.mo
usr/share/polkit-1/actions/org.freedesktop.packagekit.policy
usr/share/polkit-1/rules.d/*
