#!/bin/sh

set -e

case "${1}" in
	remove)
		# Remove the compatibility symlinks
		if [ -L '/bin/plymouth' ]; then
			rm /bin/plymouth
		fi
		if [ -L '/sbin/plymouthd' ]; then
			rm /sbin/plymouthd
		fi
		dpkg-trigger update-initramfs
		;;
	purge)
		rm -f /var/lib/plymouth/boot-duration
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
