etc/systemd/oomd.conf
usr/lib/systemd/systemd-oomd
usr/lib/systemd/system/systemd-oomd.service
usr/lib/systemd/system/systemd-oomd.socket
usr/bin/oomctl
usr/lib/sysusers.d/systemd-oom.conf
usr/share/dbus-1/system.d/org.freedesktop.oom1.conf
usr/share/dbus-1/system-services/org.freedesktop.oom1.service
usr/share/bash-completion/completions/oomctl
usr/share/zsh/vendor-completions/_oomctl
../extra/systemd-oomd-defaults/oomd.conf.d/* usr/lib/systemd/oomd.conf.d/
../extra/systemd-oomd-defaults/-.slice.d/* usr/lib/systemd/system/-.slice.d/
../extra/systemd-oomd-defaults/user@.service.d/* usr/lib/systemd/system/user@.service.d/
