debian/tmp/usr/share/system-config-printer/asyncconn.py
debian/tmp/usr/share/system-config-printer/asyncpk1.py
debian/tmp/usr/share/system-config-printer/check-device-ids.py
debian/tmp/usr/share/system-config-printer/config.py
debian/tmp/usr/share/system-config-printer/debug.py
debian/tmp/usr/share/system-config-printer/dnssdresolve.py
debian/tmp/usr/share/system-config-printer/firewallsettings.py
debian/tmp/usr/share/system-config-printer/installpackage.py
debian/tmp/usr/share/system-config-printer/killtimer.py
debian/tmp/usr/share/system-config-printer/PhysicalDevice.py
debian/tmp/usr/share/system-config-printer/ppdippstr.py
debian/tmp/usr/share/system-config-printer/probe_printer.py
#debian/tmp/usr/share/system-config-printer/profile-ppds.py
debian/tmp/usr/share/system-config-printer/pysmb.py
debian/tmp/usr/share/system-config-printer/SearchCriterion.py
debian/tmp/usr/share/system-config-printer/smburi.py
debian/tmp/usr/share/system-config-printer/statereason.py
debian/tmp/usr/share/system-config-printer/xml/*
debian/tmp/etc/dbus-1/system.d/*.conf
debian/tmp/usr/share/dbus-1
debian/tmp/usr/bin/scp-dbus-service

debian/local/source_system-config-printer.py /usr/share/apport/package-hooks/
