etc/systemd/homed.conf
usr/bin/homectl
usr/bin/systemd-home-fallback-shell
usr/lib/*/security/pam_systemd_home.so
usr/lib/systemd/systemd-homed
usr/lib/systemd/systemd-homework
usr/lib/systemd/system/systemd-homed.service
usr/lib/systemd/system/systemd-homed-activate.service
usr/lib/systemd/system/systemd-homed-firstboot.service
usr/share/dbus-1/system.d/org.freedesktop.home1.conf
usr/share/dbus-1/system-services/org.freedesktop.home1.service
usr/share/polkit-1/actions/org.freedesktop.home1.policy
usr/share/bash-completion/completions/homectl
../extra/pam-configs/systemd-homed usr/share/pam-configs/
