#!/bin/sh
set -e
grub-mkconfig -o /boot/grub/grub.cfg "$@"
# If we have some GRUB config in the Ubuntu EFI folder, also update that
if [ -d "/boot/efi/EFI/ubuntu/grub" ]; then
  grub-mkconfig -o /boot/efi/EFI/ubuntu/grub/grub.cfg "$@"
fi
