<?xml version="1.0"?>
<theme name="Classic Onboard" format="1.3">
    <color_scheme>Classic Onboard</color_scheme>
    <key_style>flat</key_style>
    <roundrect_radius>0</roundrect_radius>
    <key_fill_gradient>8</key_fill_gradient>
    <key_stroke_gradient>40</key_stroke_gradient>
    <key_gradient_direction>-3</key_gradient_direction>
    <key_label_font></key_label_font>
    <key_label_overrides></key_label_overrides>
</theme>
