<?xml version="1.0"?>
<theme name="High Contrast, Inverse" format="1.3">
    <color_scheme>HighContrastInverseBlack</color_scheme>
    <key_style>flat</key_style>
    <roundrect_radius>25</roundrect_radius>
    <key_size>95.0</key_size>
    <key_fill_gradient>30</key_fill_gradient>
    <key_stroke_gradient>70</key_stroke_gradient>
    <key_gradient_direction>-3</key_gradient_direction>
    <key_label_font>Normal bold</key_label_font>
    <key_label_overrides></key_label_overrides>
</theme>
