<?xml version="1.0"?>
<theme name="Low Contrast" format="1.3">
    <color_scheme>LowContrast</color_scheme>
    <key_style>flat</key_style>
    <roundrect_radius>30</roundrect_radius>
    <key_fill_gradient>30</key_fill_gradient>
    <key_stroke_gradient>70</key_stroke_gradient>
    <key_gradient_direction>-3</key_gradient_direction>
    <key_label_font></key_label_font>
    <key_label_overrides></key_label_overrides>
</theme>
