.TH check-language-support 1 "September 23, 2009"  "version 0.1"
.SH NAME
\fBcheck-language-support\fP \- returns the list of missing packages in order to provide a complete language environment
.SH SYNOPSIS
.B check-language-support
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-l\fR LANGUAGE, \fB\-\-language\fR=\fILANGUAGE\fR
target language code - if omitted, check for all languages on the system
.TP
\fB\-d\fR DATADIR, \fB\-\-datadir\fR=\fIDATADIR\fR
use an alternative data directory instead of the default
.B /usr/share/language\-selector
.TP
\fB\-a\fR, \fB\-\-all\fR
check all available languages
.TP
\fB\-\-show\-installed\fR
show installed packages as well as missing ones
.SH AUTHOR
This manpage has been written by Arne Goetje <arne@ubuntu.com>
