.TH gnome-language-selector 1 "August 24, 2009"  "version 0.1"
.SH NAME
\fBgnome\-language\-selector\fP \- graphical language selection utility
.SH SYNOPSIS
.B gnome\-language\-selector
[\fIOPTIONS\fP]
.SH DESCRIPTION
\fBgnome-language-selector\fP is a graphical utility that allows a user to set a default language for the system interface and to add additional language packs, spelling tools and additional fonts.
.SH OPTIONS
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-n, \-\-no\-verify\-installed\-lang\-support
do not verify installed language support
.TP
.B \-d DATADIR, \-\-datadir=DATADIR
use an alternative data directory instead of the default
.B /usr/share/language\-selector
.SH AUTHOR
This manpage has been written by Alex Lourie (djay.il (at) gmail.com)
