/*
 * Generated by gdbus-codegen 2.47.5. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __EPHY_SHELL_SEARCH_PROVIDER_GENERATED_H__
#define __EPHY_SHELL_SEARCH_PROVIDER_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Shell.SearchProvider2 */

#define EPHY_TYPE_SHELL_SEARCH_PROVIDER2 (ephy_shell_search_provider2_get_type ())
#define EPHY_SHELL_SEARCH_PROVIDER2(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2, EphyShellSearchProvider2))
#define EPHY_IS_SHELL_SEARCH_PROVIDER2(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2))
#define EPHY_SHELL_SEARCH_PROVIDER2_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2, EphyShellSearchProvider2Iface))

struct _EphyShellSearchProvider2;
typedef struct _EphyShellSearchProvider2 EphyShellSearchProvider2;
typedef struct _EphyShellSearchProvider2Iface EphyShellSearchProvider2Iface;

struct _EphyShellSearchProvider2Iface
{
  GTypeInterface parent_iface;

  gboolean (*handle_activate_result) (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_identifier,
    const gchar *const *arg_terms,
    guint arg_timestamp);

  gboolean (*handle_get_initial_result_set) (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_terms);

  gboolean (*handle_get_result_metas) (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_identifiers);

  gboolean (*handle_get_subsearch_result_set) (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_previous_results,
    const gchar *const *arg_terms);

  gboolean (*handle_launch_search) (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_terms,
    guint arg_timestamp);

};

GType ephy_shell_search_provider2_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *ephy_shell_search_provider2_interface_info (void);
guint ephy_shell_search_provider2_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void ephy_shell_search_provider2_complete_get_initial_result_set (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *results);

void ephy_shell_search_provider2_complete_get_subsearch_result_set (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *results);

void ephy_shell_search_provider2_complete_get_result_metas (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    GVariant *metas);

void ephy_shell_search_provider2_complete_activate_result (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation);

void ephy_shell_search_provider2_complete_launch_search (
    EphyShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void ephy_shell_search_provider2_call_get_initial_result_set (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_terms,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ephy_shell_search_provider2_call_get_initial_result_set_finish (
    EphyShellSearchProvider2 *proxy,
    gchar ***out_results,
    GAsyncResult *res,
    GError **error);

gboolean ephy_shell_search_provider2_call_get_initial_result_set_sync (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_terms,
    gchar ***out_results,
    GCancellable *cancellable,
    GError **error);

void ephy_shell_search_provider2_call_get_subsearch_result_set (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_previous_results,
    const gchar *const *arg_terms,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ephy_shell_search_provider2_call_get_subsearch_result_set_finish (
    EphyShellSearchProvider2 *proxy,
    gchar ***out_results,
    GAsyncResult *res,
    GError **error);

gboolean ephy_shell_search_provider2_call_get_subsearch_result_set_sync (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_previous_results,
    const gchar *const *arg_terms,
    gchar ***out_results,
    GCancellable *cancellable,
    GError **error);

void ephy_shell_search_provider2_call_get_result_metas (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_identifiers,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ephy_shell_search_provider2_call_get_result_metas_finish (
    EphyShellSearchProvider2 *proxy,
    GVariant **out_metas,
    GAsyncResult *res,
    GError **error);

gboolean ephy_shell_search_provider2_call_get_result_metas_sync (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_identifiers,
    GVariant **out_metas,
    GCancellable *cancellable,
    GError **error);

void ephy_shell_search_provider2_call_activate_result (
    EphyShellSearchProvider2 *proxy,
    const gchar *arg_identifier,
    const gchar *const *arg_terms,
    guint arg_timestamp,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ephy_shell_search_provider2_call_activate_result_finish (
    EphyShellSearchProvider2 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean ephy_shell_search_provider2_call_activate_result_sync (
    EphyShellSearchProvider2 *proxy,
    const gchar *arg_identifier,
    const gchar *const *arg_terms,
    guint arg_timestamp,
    GCancellable *cancellable,
    GError **error);

void ephy_shell_search_provider2_call_launch_search (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_terms,
    guint arg_timestamp,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean ephy_shell_search_provider2_call_launch_search_finish (
    EphyShellSearchProvider2 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean ephy_shell_search_provider2_call_launch_search_sync (
    EphyShellSearchProvider2 *proxy,
    const gchar *const *arg_terms,
    guint arg_timestamp,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define EPHY_TYPE_SHELL_SEARCH_PROVIDER2_PROXY (ephy_shell_search_provider2_proxy_get_type ())
#define EPHY_SHELL_SEARCH_PROVIDER2_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_PROXY, EphyShellSearchProvider2Proxy))
#define EPHY_SHELL_SEARCH_PROVIDER2_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_PROXY, EphyShellSearchProvider2ProxyClass))
#define EPHY_SHELL_SEARCH_PROVIDER2_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_PROXY, EphyShellSearchProvider2ProxyClass))
#define EPHY_IS_SHELL_SEARCH_PROVIDER2_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_PROXY))
#define EPHY_IS_SHELL_SEARCH_PROVIDER2_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_PROXY))

typedef struct _EphyShellSearchProvider2Proxy EphyShellSearchProvider2Proxy;
typedef struct _EphyShellSearchProvider2ProxyClass EphyShellSearchProvider2ProxyClass;
typedef struct _EphyShellSearchProvider2ProxyPrivate EphyShellSearchProvider2ProxyPrivate;

struct _EphyShellSearchProvider2Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  EphyShellSearchProvider2ProxyPrivate *priv;
};

struct _EphyShellSearchProvider2ProxyClass
{
  GDBusProxyClass parent_class;
};

GType ephy_shell_search_provider2_proxy_get_type (void) G_GNUC_CONST;

void ephy_shell_search_provider2_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
EphyShellSearchProvider2 *ephy_shell_search_provider2_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
EphyShellSearchProvider2 *ephy_shell_search_provider2_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void ephy_shell_search_provider2_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
EphyShellSearchProvider2 *ephy_shell_search_provider2_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
EphyShellSearchProvider2 *ephy_shell_search_provider2_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define EPHY_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON (ephy_shell_search_provider2_skeleton_get_type ())
#define EPHY_SHELL_SEARCH_PROVIDER2_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON, EphyShellSearchProvider2Skeleton))
#define EPHY_SHELL_SEARCH_PROVIDER2_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON, EphyShellSearchProvider2SkeletonClass))
#define EPHY_SHELL_SEARCH_PROVIDER2_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON, EphyShellSearchProvider2SkeletonClass))
#define EPHY_IS_SHELL_SEARCH_PROVIDER2_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON))
#define EPHY_IS_SHELL_SEARCH_PROVIDER2_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EPHY_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON))

typedef struct _EphyShellSearchProvider2Skeleton EphyShellSearchProvider2Skeleton;
typedef struct _EphyShellSearchProvider2SkeletonClass EphyShellSearchProvider2SkeletonClass;
typedef struct _EphyShellSearchProvider2SkeletonPrivate EphyShellSearchProvider2SkeletonPrivate;

struct _EphyShellSearchProvider2Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  EphyShellSearchProvider2SkeletonPrivate *priv;
};

struct _EphyShellSearchProvider2SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType ephy_shell_search_provider2_skeleton_get_type (void) G_GNUC_CONST;

EphyShellSearchProvider2 *ephy_shell_search_provider2_skeleton_new (void);


G_END_DECLS

#endif /* __EPHY_SHELL_SEARCH_PROVIDER_GENERATED_H__ */
