/* main.c generated by valac 0.22.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <locale.h>
#include <libnotify/notify.h>

#include "indicator-sound-service.h"
#include "config.h"

int
main (int argc, char ** argv) {
	gint result = 0;
	IndicatorSoundService* service = NULL;

	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	setlocale (LC_ALL, "");
	bindtextdomain (GETTEXT_PACKAGE, GNOMELOCALEDIR);

	/* Initialize libnotify */
	notify_init ("indicator-sound");

	MediaPlayerList * playerlist = NULL;

	if (g_strcmp0("lightdm", g_get_user_name()) == 0) {
		playerlist = MEDIA_PLAYER_LIST(media_player_list_greeter_new());
	} else {
		playerlist = MEDIA_PLAYER_LIST(media_player_list_mpris_new());
	}

	service = indicator_sound_service_new (playerlist);
	result = indicator_sound_service_run (service);

	g_object_unref(playerlist);
	g_object_unref(service);

	return result;
}


