on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/elementary/docker:stable

    steps:
    - name: Checkout the import-list
      uses: actions/checkout@v4
      with:
        ref: import-list-bionic
        fetch-depth: 1
    - name: Get the list of packages
      run: |
        cp bionic/packages_to_import /tmp/patched-packages
    - name: Install Dependencies
      run: |
        sed -i 's/^\(Types: deb\)$/\1 deb-src/g' /etc/apt/sources.list.d/ubuntu.sources
        apt update
        apt install -y git python3-launchpadlib python3-apt python3-github python3-debian
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Verify that we are shipping the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      run: |
        while IFS=":" read -r line upstream_series; do
            echo "Checking version for $line"
            python3 ./get-latest-version.py "$line" "bionic" "$upstream_series"
        done < "/tmp/patched-packages"
