on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:stable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y curl devscripts dpkg-dev build-essential git quilt lsb-release ubuntu-keyring wget openssh-client
    - name: Build
      run: |
        mkdir /tmp/os-patches
        GIT_WEB_URL="https://github.com/elementary/os-patches" BASE_TMP_DIR=/tmp/os-patches GPG_KEYRING=/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg ./package-importer import-list-bionic
