on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    container:
      image: elementary/docker:stable

    steps:
    - name: Checkout the import-list
      uses: actions/checkout@v1
      with:
        ref: import-list-focal
        fetch-depth: 1
    - name: Get the list of packages
      run: |
        cp focal/packages_to_import /tmp/patched-packages
    - name: Checkout the repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y git python3-launchpadlib python3-apt python3-github
    - name: Verify that we are shipping the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: elementary/os-patches
      run: |
        while IFS=":" read -r line upstream_series; do
            echo "Checking version for $line"
            python3 ./get-latest-version.py "$line" "focal" "$upstream_series"
        done < "/tmp/patched-packages"
